name: CI Beta

on:
  push:
    branches:
      - beta

jobs:
    Lint-Project:
        runs-on: ubuntu-latest
        steps:
         - name: "Update Image"
           if: ${{ env.ACT }}
           run: |
              sudo apt update
         - uses: actions/checkout@v4
           with:
             fetch-depth: 50
         - name: Lint lua files
           uses: nebularg/actions-luacheck@v1.1.2
           with:
             args: "--no-color -q --no-self"
             annotate: warning
         - name: Create alpha package
           uses: BigWigsMods/packager@master
           with:
              args: -d -z
         - name: Upload alpha package to artifacts
           uses: actions/upload-artifact@v3
           with:
             name: SwitchSwitch-Beta.zip
             path: |
               .release/*
         - name: Remove old artifacts
           uses: c-hive/gha-remove-artifacts@v1
           with:
             age: '3 month'
             skip-tags: true
      Deploy-Packages:
        if: startsWith(github.ref, 'refs/tags/')
        runs-on: ubuntu-latest
        needs: Lint-Project
        steps:
         - uses: actions/checkout@v4
           with:
             fetch-depth: 50
         - name: Upload locales strings to CurseForge
           run: ./CurseForge_UpldateTranslations.sh
           env:
             CF_API_KEY: ${{ secrets.CF_API_KEY }}
         - name: Create and uploat to curseforge
           uses: BigWigsMods/packager@master
           env:
             CF_API_KEY: ${{ secrets.CF_API_KEY }}
             WOWI_API_TOKEN : ${{ secrets.WOWI_API_TOKEN }}
             GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
